### ISSUE TITLE
[BUG]  -disable-history not working

### ISSUE THREAD

**Issue by haennes** [davatorium/rofi#1995]
### Rofi version (rofi -v)

Version: 1.7.5+wayland3

### Configuration

https://gist.github.com/haennes/9b100643da1e93aa4ea9845688002d83

### Theme

https://gist.github.com/haennes/494f96e6a339701f9bb2422639d0c223

### Launch command

rofi -dmenu -disable-history -no-fixed-num-lines -l 1 -i  -input /dev/null -password -p "Passphrase:"

### Step to reproduce

run `rofi -dmenu -disable-history -no-fixed-num-lines -l 1 -i  -input /dev/null -password -p "Passphrase:" `

### Expected behavior

doesnt write anything to `$XDG_CACHE_HOME/rofi-entry-history.txt`  (i.e. `~/.cache/rofi-entry-history.txt`)

### Actual behavior

outputs a password to this file

### Additional information

I actually am on wayland, but this is completely irrelevant for this bug 

### Using wayland display server protocol

- [X] No, I don't use the wayland display server protocol

### I've checked if the issue exists in the latest stable release

- [X] Yes, I have checked the problem exists in the latest stable version

**Comment by DaveDavenport** [comment]
good catch, the entry history should also be disabled.

**Comment by haennes** [comment]
Sorry, but I have no clue on how to fix that myself.....
I tried but failed to understand the code structure :/

**Comment by DaveDavenport** [comment]
ill fix it when I have time.

**Comment by DaveDavenport** [comment]
commited code that should fix the code disabling it when -password is passed.
It also disables it with -disable-history.

**Comment by haennes** [comment]
doesnt fix it on my machine. Have actually confirmed i am using the right rofi using nix repl....
Behaviour is still the same as before.
I am not sure enough though, can you reproduce? (still same cmd as in original post)
This shouldnt have anything to do with me using wayland as it is such a core functionality (i am using this git repo as a source anyways), right?

**Comment by DaveDavenport** [comment]
you are not using this repository.  you are using @lbonn his fork.

**Comment by trinitronx** [comment]
> you are not using this repository. you are using @lbonn his fork.

Yes, the fixes will have to be merged into the [`lbonn/rofi`][1] fork from this repo (`git merge upstream/next`).

[1]: https://github.com/lbonn/rofi

**Comment by jmonroynieto** [comment]
Would you consider creating a command to disable it once it is already running? A command to send a message to toggle which would be caught by the daemon could be fantastic. I am running it as a systemd service and having to kill it and then relaunch it is a bit of a friction point.

I envision a timer too. my use case involves fetching passwords from my manager, having it so that I don't have to toggle it back again sounds very appealing. I'm not a C developer so I can't offer a PR in any reasonable timeframe.

**Comment by DaveDavenport** [comment]
@jmonroynieto  I don't understand your request in the context of rofi. But please make a new discussion on this (see guidelines!) , so we don't pollute this issue.

**Comment by lbonn** [comment]
This can be closed now that this is released in every version
